#!/usr/bin/python
# -*- coding: UTF-8 -*-
"""
第一种方法：
author：BaiXiaorong
time：2019-9-20
"""
li=[]
for i in range(1,5):
	for g in range(1,5):
		if (i==g):
			continue
		else:
			for j in range(1,5):
				if (j != i and j != g):
					st=str(i)+str(g)+str(j)
					li.append(st)
				else:
					continue
print(li)

"""
第二种方法：
author：BaiXiaorong
time：2019-9-20
"""
for i in range(1,5):
    for j in range(1,5):
        for k in range(1,5):
            if( i != k ) and (i != j) and (j != k):
                print i,j,k

