#!/usr/bin/python
# -*- coding: UTF-8 -*-
li=[]
for i in range(1,5):
	for g in range(1,5):
		if (i==g):
			continue
		else:
			for j in range(1,5):
				if (j != i and j != g):
					st=str(i)+str(g)+str(j)
					li.append(st)
				else:
					continue
print(li)




